php:
  build: .
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./:/var/www/html
  links:
    - db

db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123
   - MYSQL_DATABASE=conpresp_db