php:
  build: .
  ports:
    - "80:80"
  volumes:
    - ./:/var/www/html/
  links:
    - db
db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_DATABASE=conpresp_db
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
